name: Tests

on:
  push:
    tags:
    branches:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # we need control over the path, since stacktrace tests rely on it
        path: github.com/samber/oops

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.3
        stable: false

    - name: Build
      working-directory: ./github.com/samber/oops
      run: make build

    - name: Test
      working-directory: ./github.com/samber/oops
      run: make test

    - name: Test
      working-directory: ./github.com/samber/oops
      run: make coverage

    - name: Codecov
      working-directory: ./github.com/samber/oops
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cover.out
        flags: unittests
        verbose: true
